### ISSUE TITLE
Markers and HideSingleGroupMarker

### ISSUE THREAD

**Issue by mmlachak** [jmelosegui/GooglemapMvc#93] opened 2016-04-11 14:32 UTC
I had a map with markers that was displaying correctly if I set the HideSingleGroupMarker to true.  It grouped my markers by country and when I clicked on a group marker individual markers for that country displayed correctly,  This functionality does not work anymore.  All I get is single markers when the HideSingleGroupMarker is set to true. I did not change any code or the version of your maps control. ANy help or guidance would be appreciated....

 See attached:
[jmelosegui Bug - HideSIngleGroupMarker.docx](https://github.com/jmelosegui/GooglemapMvc/files/213174/jmelosegui.Bug.-.HideSIngleGroupMarker.docx)

**Comment by jmelosegui** [comment] 2016-04-30 20:24
I cannot reproduce your issue. Could you please provide the steps to reproduce this issue, maybe a project here in github showing the error so I can fork  it and try to help you with.

**Comment by jmelosegui** [comment] 2016-05-02 17:05
:eyes:

**Comment by jmelosegui** [comment] 2016-05-03 16:53
I will close this issue now. Feel free to reopen it if you want to address it again.

**Closed by jmelosegui** 2016-05-03 16:53 UTC
Labels: question
